#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0
"""Generate the NanoKVM ION reserved-memory property.

U-Boot does not reserve the Linux device tree's ION node while it is loading
the FIT ramdisk and FDT.  Treat its observed runtime/load window as unavailable
instead of blindly growing ION down from the top of DRAM.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path


MIB = 1024 * 1024
MIN_SIZE_MIB = 22
MAX_SIZE_MIB = 112
MIN_RTOS_RAM_SIZE_MIB = 1
MAX_RTOS_RAM_SIZE_MIB = 16
MAX_FRAMEBUFFER_SIZE_MIB = 32
MIN_GPIO_I2C_DELAY_US = 1
MAX_GPIO_I2C_DELAY_US = 100


@dataclass(frozen=True)
class Region:
    start: int
    end: int

    @property
    def size(self) -> int:
        return self.end - self.start


@dataclass(frozen=True)
class MemoryLayout:
    ion: Region
    rtos: Region
    framebuffer: Region | None


# 0x80000000-0x85000000 remains available for the kernel and early FIT work.
# The entire 0x8c000000-0x8ce00000 range is conservatively excluded because
# U-Boot relocates there and has placed the FIT ramdisk/FDT there in production.
# C906L occupies 0x8fe00000-0x90000000.
DRAM = Region(0x80000000, 0x90000000)
EXPANSION_ARENA = Region(0x85000000, 0x8C000000)
LEGACY_ARENA_START = 0x8CE00000
STATIC_FORBIDDEN_REGIONS = (
    Region(0x80000000, 0x85000000),
    Region(0x8C000000, 0x8CE00000),
)


def regions_overlap(left: Region, right: Region) -> bool:
    return left.start < right.end and right.start < left.end


def select_layout(
    ion_size_mib: int,
    rtos_ram_size_mib: int = 2,
    framebuffer_size_mib: int = 0,
) -> MemoryLayout:
    if not MIN_SIZE_MIB <= ion_size_mib <= MAX_SIZE_MIB:
        raise ValueError(
            f"ION size must be between {MIN_SIZE_MIB} and {MAX_SIZE_MIB} MiB"
        )
    if not MIN_RTOS_RAM_SIZE_MIB <= rtos_ram_size_mib <= MAX_RTOS_RAM_SIZE_MIB:
        raise ValueError(
            "RTOS RAM size must be between "
            f"{MIN_RTOS_RAM_SIZE_MIB} and {MAX_RTOS_RAM_SIZE_MIB} MiB"
        )
    if not 0 <= framebuffer_size_mib <= MAX_FRAMEBUFFER_SIZE_MIB:
        raise ValueError(
            f"framebuffer size must be between 0 and {MAX_FRAMEBUFFER_SIZE_MIB} MiB"
        )

    rtos = Region(DRAM.end - rtos_ram_size_mib * MIB, DRAM.end)
    legacy_arena = Region(LEGACY_ARENA_START, rtos.start)
    size = ion_size_mib * MIB
    framebuffer_size = framebuffer_size_mib * MIB
    if size <= legacy_arena.size and framebuffer_size <= EXPANSION_ARENA.size:
        # Preserve the production layout for 48 MiB and smaller sizes.
        ion = Region(legacy_arena.end - size, legacy_arena.end)
        framebuffer = (
            Region(EXPANSION_ARENA.start, EXPANSION_ARENA.start + framebuffer_size)
            if framebuffer_size
            else None
        )
    elif size <= EXPANSION_ARENA.size:
        # Keep a stable low base and pack an optional framebuffer after ION.
        ion = Region(EXPANSION_ARENA.start, EXPANSION_ARENA.start + size)
        framebuffer = (
            Region(ion.end, ion.end + framebuffer_size) if framebuffer_size else None
        )
    else:
        raise ValueError(f"no safe contiguous arena for {ion_size_mib} MiB of ION")

    if framebuffer is not None and framebuffer.end > EXPANSION_ARENA.end:
        raise ValueError(
            f"ION ({ion_size_mib} MiB) and framebuffer "
            f"({framebuffer_size_mib} MiB) do not fit in a safe arena"
        )

    for forbidden in (*STATIC_FORBIDDEN_REGIONS, rtos):
        if regions_overlap(ion, forbidden):
            raise ValueError(
                f"computed ION region {ion.start:#x}-{ion.end:#x} overlaps "
                f"reserved region {forbidden.start:#x}-{forbidden.end:#x}"
            )
        if framebuffer is not None and regions_overlap(framebuffer, forbidden):
            raise ValueError(
                f"computed framebuffer region {framebuffer.start:#x}-{framebuffer.end:#x} "
                f"overlaps reserved region {forbidden.start:#x}-{forbidden.end:#x}"
            )
    if framebuffer is not None and regions_overlap(ion, framebuffer):
        raise ValueError("computed ION and framebuffer regions overlap")
    return MemoryLayout(ion=ion, rtos=rtos, framebuffer=framebuffer)


def render_dtsi(
    ion_size_mib: int,
    rtos_ram_size_mib: int,
    framebuffer_size_mib: int,
    gpio_i2c_delay_us: int,
) -> str:
    if not MIN_GPIO_I2C_DELAY_US <= gpio_i2c_delay_us <= MAX_GPIO_I2C_DELAY_US:
        raise ValueError(
            "GPIO I2C delay must be between "
            f"{MIN_GPIO_I2C_DELAY_US} and {MAX_GPIO_I2C_DELAY_US} microseconds"
        )
    layout = select_layout(ion_size_mib, rtos_ram_size_mib, framebuffer_size_mib)
    kernel_size = layout.rtos.start - DRAM.start
    output = (
        "/* Generated by nanokvm_ion_layout.py; do not edit. */\n"
        f"#define CVITEK_GPIO_I2C_DELAY_US {gpio_i2c_delay_us}\n"
        f"/* ION: {ion_size_mib} MiB @ {layout.ion.start:#010x}-"
        f"{layout.ion.end - 1:#010x}; RTOS: {rtos_ram_size_mib} MiB @ "
        f"{layout.rtos.start:#010x}-{layout.rtos.end - 1:#010x}. */\n"
        "&{/memory@80000000} {\n"
        f"\treg = <0x0 {DRAM.start:#010x} 0x0 {kernel_size:#010x}>;\n"
        "};\n\n"
        "&{/fast_image} {\n"
        f"\treg = <0x0 {layout.rtos.start:#010x} 0x0 {layout.rtos.size:#010x}>;\n"
        "};\n\n"
        "&ion_reserved {\n"
        f"\treg = <0x0 {layout.ion.start:#010x} 0x0 {layout.ion.size:#010x}>;\n"
        "\t/delete-property/ size;\n"
        "};\n\n"
    )
    if layout.framebuffer is None:
        output += (
            "&fb_reserved {\n\tstatus = \"disabled\";\n};\n\n"
            "&cvi_fb {\n\tstatus = \"disabled\";\n};\n"
        )
    else:
        output += (
            "&fb_reserved {\n"
            f"\talloc-ranges = <0x0 {layout.framebuffer.start:#010x} 0x0 "
            f"{layout.framebuffer.size:#010x}>;\n"
            f"\tsize = <0x0 {layout.framebuffer.size:#010x}>;\n"
            "\tstatus = \"okay\";\n};\n\n"
            "&cvi_fb {\n\tstatus = \"okay\";\n};\n"
        )
    return output


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ion-size-mib", type=int, required=True)
    parser.add_argument("--rtos-ram-size-mib", type=int, required=True)
    parser.add_argument("--framebuffer-size-mib", type=int, required=True)
    parser.add_argument("--gpio-i2c-delay-us", type=int, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    output = render_dtsi(
        args.ion_size_mib,
        args.rtos_ram_size_mib,
        args.framebuffer_size_mib,
        args.gpio_i2c_delay_us,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="ascii")


if __name__ == "__main__":
    main()
